home_app/urls.py
from django.urls import path
from . import views

urlpatterns = [    
    path('', views.home, name='home'),
]

orm_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('tags/', include('etiquetas_app.urls')),
    path('products/', include('productos_app.urls')),
    path('cat/', include('categoria_app.urls')),
    path('perfil/', include('perfil_app.urls')),
    path('carrito/', include('carrito_app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productos_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('productos/', views.ProductoListView.as_view(), name='producto_list'),
    path('productos/<int:pk>/', views.ProductoDetailView.as_view(), name='producto_detail'),
    path('productos/crear/', views.producto_create, name='producto_create'),
    path('productos/<int:pk>/editar/', views.producto_edit, name='producto_edit'),
    path('productos/<int:pk>/eliminar/', views.producto_delete, name='producto_delete'),
]

carrito_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from productos_app.models import Producto
from django.contrib.sessions.models import Session
import uuid

User = get_user_model()


class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='carritos')
    session = models.ForeignKey(Session, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        if self.usuario:
            return f"Carrito de {self.usuario.username}"
        else:
            return "Carrito sin usuario asociado"



class CarritoItem(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='carrito_item')
    carrito = models.ForeignKey('Carrito', on_delete=models.CASCADE, related_name='items')
    cantidad = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)

productos_app/models.py
from django.db import models
from django.utils import timezone
from categoria_app.models import Categoria



class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='productos')
    precio = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    descripcion = models.TextField(default='Sin descripción.')
    stock = models.PositiveIntegerField(default=0)
    fecha_creacion = models.DateTimeField(default=timezone.now) 
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    
    @property
    def imagen_url(self):
        if self.imagen and hasattr(self.imagen, 'url'):
            return self.imagen.url
        return '/static/img/producto_default.png'

productos_app/forms.py
from django import forms
from .models import Producto, Categoria

class ProductoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args, **kwargs)
        self.fields['categoria'].queryset = Categoria.objects.all()
        self.fields['categoria'].widget = forms.Select(attrs={'class': 'form-control'}, choices=self.get_categorias_with_subcategorias())

    def get_categorias_with_subcategorias(self):
        categorias_with_subcategorias = []
        categorias = Categoria.objects.filter(parent__isnull=True)
        for categoria in categorias:
            subcategorias = categoria.subcategorias.all()
            if subcategorias:
                subcategoria_choices = [(subcategoria.id, f'{subcategoria.nombre} ({categoria.nombre})') for subcategoria in subcategorias]
                categorias_with_subcategorias.append((categoria.nombre, subcategoria_choices))
            else:
                categorias_with_subcategorias.append((categoria.nombre, [(categoria.id, categoria.nombre)]))
        return categorias_with_subcategorias

    class Meta:
        model = Producto
        fields = ['nombre', 'categoria', 'precio', 'descripcion', 'stock', 'imagen', 'disponible']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'stock': forms.NumberInput(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'disponible': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

productos_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required

from .models import Producto
from .forms import ProductoForm

# Create your views here.




class ProductoListView(ListView):
    model = Producto
    template_name = 'productos_app/producto_list.html'
    context_object_name = 'productos'

class ProductoDetailView(DetailView):
    model = Producto
    template_name = 'productos_app/producto_detail.html'
    context_object_name = 'producto'

@login_required
def producto_create(request):
    if request.user.perfil.rol != 'VE':
        return render(request, 'acceso_denegado.html')  # Ajusta esto según tus necesidades

    if request.method == "POST":
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('producto_list')
    else:
        form = ProductoForm()
    
    return render(request, 'productos_app/producto_create.html', {'form': form})

def producto_edit(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == "POST":
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('producto_list')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'productos_app/producto_edit.html', {'form': form}, )

def producto_delete(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == "POST":
        producto.delete()
        return redirect('producto_list')
    return render(request, 'productos_app/producto_delete.html', {'producto': producto})

productos_app/templates/productos_app/producto_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Crear Producto</title>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="text-white">Crear Producto</h1>
        <form method="POST" enctype="multipart/form-data" class="text-white">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.nombre.id_for_label }}">Nombre</label>
                {{ form.nombre }}
            </div>
            <div class="form-group">
                <label for="{{ form.categoria.id_for_label }}">Categoría</label>
                {{ form.categoria }}
            </div>
            <div class="form-group">
                <label for="{{ form.precio.id_for_label }}">Precio</label>
                {{ form.precio }}
            </div>
            <div class="form-group">
                <label for="{{ form.descripcion.id_for_label }}">Descripción</label>
                {{ form.descripcion }}
            </div>
            <div class="form-group">
                <label for="{{ form.stock.id_for_label }}">Stock</label>
                {{ form.stock }}
            </div>
            <div class="form-group">
                <label for="{{ form.imagen.id_for_label }}">Imagen</label>
                {{ form.imagen }}
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="{{ form.disponible.id_for_label }}" name="{{ form.disponible.name }}">
                <label class="form-check-label" for="{{ form.disponible.id_for_label }}">Disponible</label>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Crear Producto</button>
        </form>
    </div>
{% endblock %}

productos_app/templates/productos_app/producto_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Eliminar Producto</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-white">Eliminar Producto</h1>
    <p>¿Estás seguro de que deseas eliminar el producto "{{ producto.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'producto_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

productos_app/templates/productos_app/producto_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Detalle del Producto</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-white">Detalle del Producto</h1>
    <div class="card mb-3 card-bg">
        <div class="row no-gutters">
            <div class="col-md-4 d-flex align-items-center">
                {% if producto.imagen %}
                    <img src="{{ producto.imagen_url }}" class="card-img img-fluid" alt="{{ producto.nombre }}" style="max-width: 400px; margin: auto;">
                {% else %}
                    <img src="{% static 'img/producto_default.png' %}" class="card-img" alt="{{ producto.nombre }}" style="max-width: 150px; margin: auto;">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ producto.nombre }}</h5>
                    <p class="card-text"><strong>Categoría:</strong> {{ producto.categoria }}</p>
                    <p class="card-text"><strong>Precio:</strong> ${{ producto.precio }}</p>
                    <p class="card-text"><strong>Descripción:</strong> {{ producto.descripcion }}</p>
                    <p class="card-text"><strong>Stock:</strong> {{ producto.stock }}</p>
                    <p class="card-text"><strong>Fecha de Creación:</strong> {{ producto.fecha_creacion }}</p>
                    <p class="card-text">
                        <strong>Disponibilidad:</strong>
                        {% if producto.disponible %}
                            <span class="badge badge-success text-success">Disponible</span>
                        {% else %}
                            <span class="badge badge-danger text-danger">No Disponible</span>
                        {% endif %}
                    </p>
                    <div class="form-group">
                        <label for="cantidad">Cantidad:</label>
                        <input type="number" id="cantidad" name="cantidad" value="1" min="1" max="{{ producto.stock }}" class="form-control">
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if user.perfil.rol == 'VE' %}
                            <a href="{% url 'producto_edit' pk=producto.pk %}" class="btn btn-secondary">Editar Producto</a>
                            <a href="{% url 'producto_delete' pk=producto.pk %}" class="btn btn-danger">Eliminar Producto</a>
                        {% endif %}
                        <form action="{% url 'agregar_al_carrito' producto.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="cantidad" id="id_cantidad">
                            <button type="submit" class="btn btn-primary">Agregar al Carrito</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const cantidadInput = document.getElementById('cantidad');
        const cantidadHidden = document.getElementById('id_cantidad');
        
        cantidadInput.addEventListener('change', function() {
            cantidadHidden.value = this.value;
        });
    });
</script>

productos_app/templates/productos_app/producto_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Editar Producto</title>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="text-white">Editar Producto</h1>
        <form method="POST" enctype="multipart/form-data" class="text-white">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.nombre.id_for_label }}">Nombre</label>
                {{ form.nombre }}
            </div>
            <div class="form-group">
                <label for="{{ form.categoria.id_for_label }}">Categoría</label>
                {{ form.categoria }}
            </div>
            <div class="form-group">
                <label for="{{ form.precio.id_for_label }}">Precio</label>
                {{ form.precio }}
            </div>
            <div class="form-group">
                <label for="{{ form.descripcion.id_for_label }}">Descripción</label>
                {{ form.descripcion }}
            </div>
            <div class="form-group">
                <label for="{{ form.stock.id_for_label }}">Stock</label>
                {{ form.stock }}
            </div>
            <div class="form-group">
                <label for="{{ form.imagen.id_for_label }}">Imagen</label>
                {{ form.imagen }}
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="{{ form.disponible.id_for_label }}" name="{{ form.disponible.name }}">
                <label class="form-check-label" for="{{ form.disponible.id_for_label }}">Disponible</label>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Guardar Cambios</button>
        </form>
    </div>
{% endblock %}

productos_app/templates/productos_app/producto_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Lista de Productos</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="text-white">Lista de Productos</h1>
        {% if user.perfil.rol == 'VE' %}
            <a href="{% url 'producto_create' %}" class="btn btn-primary mr-2">Crear Producto</a>
        {% endif %}
    </div>
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <select id="categoriaFiltro" class="form-select">
                <option value="">Todas las categorías</option>
                {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <button id="ordenarPrecio" class="btn btn-secondary">Ordenar por Precio: Mayor a Menor</button>
        </div>
    </div>
    <div class="row justify-content-center" id="productos-list">
        {% for producto in productos %}
        <div class="col-12 mb-4 producto-item" data-categoria="{{ producto.categoria.id }}">
            <div class="card card-bg">
                <div class="row no-gutters">
                    <div class="col-md-4 d-flex align-items-center">
                        {% if producto.imagen %}
                            <img src="{{ producto.imagen_url }}" class="card-img m-3" alt="{{ producto.nombre }}" style="max-width: 400px; margin: auto;">
                        {% else %}
                            <img src="{% static 'img/producto_default.png' %}" class="card-img" alt="{{ producto.nombre }}" style="max-width: 150px; margin: auto;">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'producto_detail' pk=producto.pk %}" target="_blank">{{ producto.nombre }}</a></h5>
                            <p class="card-text">Precio: $<span class="precio">{{ producto.precio }}</span></p>
                            <div class="card-text text-truncate-container">
                                <p class="text-truncate" id="descripcion-{{ producto.pk }}">{{ producto.descripcion }}</p>
                                <button class="btn btn-link p-0 text-truncate-toggle" onclick="toggleDescription({{ producto.pk }})">Ver más</button>
                            </div>
                            <p class="card-text">Stock: {{ producto.stock }}</p>
                            {% if producto.disponible %}
                                <span class="badge badge-success text-success">Disponible</span>
                            {% else %}
                                <span class="badge badge-danger text-danger">No Disponible</span>
                            {% endif %}
                            <div class="d-flex justify-content-end">
                                {% if user.perfil.rol == 'VE' %}
                                    <a href="{% url 'producto_edit' pk=producto.pk %}" class="btn btn-secondary mr-2">Editar Producto</a>
                                    <a href="{% url 'producto_delete' pk=producto.pk %}" class="btn btn-danger">Eliminar Producto</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>
.text-truncate-container {
    max-height: 12.6em; /* 1.575em per line for 8 lines */
    overflow: hidden;
    position: relative;
}

.text-truncate {
    display: -webkit-box;
    -webkit-line-clamp: 8; /* Number of lines to show */
    -webkit-box-orient: vertical;
    overflow: hidden;
}

.text-truncate-toggle {
    display: block;
    cursor: pointer;
    margin-top: 0.5em;
}
</style>

<script>
function toggleDescription(pk) {
    const desc = document.getElementById('descripcion-' + pk);
    const toggleButton = desc.nextElementSibling;

    if (desc.classList.contains('text-truncate')) {
        desc.classList.remove('text-truncate');
        desc.parentElement.style.maxHeight = 'none';
        toggleButton.textContent = 'Ver menos';
    } else {
        desc.classList.add('text-truncate');
        desc.parentElement.style.maxHeight = '12.6em';
        toggleButton.textContent = 'Ver más';
    }
}

document.getElementById('categoriaFiltro').addEventListener('change', function() {
    const categoriaId = this.value;
    const productos = document.querySelectorAll('.producto-item');

    productos.forEach(producto => {
        if (categoriaId === "" || producto.getAttribute('data-categoria') === categoriaId) {
            producto.style.display = 'block';
        } else {
            producto.style.display = 'none';
        }
    });
});

let ordenarAscendente = true;

document.getElementById('ordenarPrecio').addEventListener('click', function() {
    const productosList = document.getElementById('productos-list');
    const productos = Array.from(productosList.querySelectorAll('.producto-item'));

    productos.sort((a, b) => {
        const precioA = parseFloat(a.querySelector('.precio').innerText);
        const precioB = parseFloat(b.querySelector('.precio').innerText);
        return ordenarAscendente ? precioA - precioB : precioB - precioA;
    });

    productos.forEach(producto => productosList.appendChild(producto));

    ordenarAscendente = !ordenarAscendente;
    this.textContent = ordenarAscendente ? 'Ordenar por Precio: Mayor a Menor' : 'Ordenar por Precio: Menor a Mayor';
});
</script>
{% endblock %}